// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyrcgeckvmbeftuniadr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5cmNnZWNrdm1iZWZ0dW5pYWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2MTczMzMsImV4cCI6MjA4OTE5MzMzM30.lZCE0xie34Vh2vv_DkTbatlYPr94Fvy4HFmGmE8TLxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});